continents/urls.py
from django.contrib import admin
from django.urls import path
from continents.views import ContinentsView

app_name = 'continents'

urlpatterns = [
    path('', ContinentsView.as_view(), name="home")
]

countries/urls.py
from django.contrib import admin
from django.urls import path
from countries.views import (
	CountryDetailView, 
	CountryDetailIDView,
	CountrySearchView,
    CreateCountryView
	)

urlpatterns = [
    path('register/', CreateCountryView.as_view(), name="register"),
    path('search/<query>/', CountrySearchView.as_view(), name="country_search"),
    path('<int:pk>/', CountryDetailIDView.as_view(), name="country_id_detail"),
    path('<code>/', CountryDetailView.as_view(), name="country_code_detail")
]

geographic/urls.py
from django.contrib import admin
from django.urls import path, include
from countries.views import HomeView, TagsView, CountryDetailView, CountryDetailIDView
from continents.views import ContinentsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('tags/', TagsView.as_view(), name="tags"),
    path('continents/', include("continents.urls", namespace="continents")),
    path('countries/', include("countries.urls")),
    path('people/', include("people.urls"))
]

people/urls.py
from django.urls import path, include
from people.views import register

urlpatterns = [
    path('register/', register, name="register")
]

continents/models.py
from django.db import models

# Create your models here.
class Continent(models.Model):
	name = models.CharField(max_length=255)
	translate = models.CharField(max_length=255)
	color = models.CharField(max_length=255)

	def __str__(self):
		return self.name

countries/models.py
from django.db import models

class ActiveManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(active=True)

# Create your models here.
class Country(models.Model):

	CODES_CHOICES = (
		('CO','colombia'),
		('MX','mexico'),
		('USA','estados unidos'),
		('AR','argentina'),
	)

	name = models.CharField(max_length=255)
	code = models.CharField(max_length=3, choices=CODES_CHOICES)
	continent = models.ForeignKey('continents.Continent', on_delete=models.CASCADE)
	active = models.BooleanField(default=True)
	active_manager = ActiveManager()
	objects = models.Manager()

	def __str__(self):
		return self.name

people/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
	first_name = models.CharField(max_length=255)
	nacionality = models.ManyToManyField('countries.Country')
	father = models.OneToOneField('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')

	def __str__(self):
		return self.first_name

countries/forms.py
from django import forms
from countries.models import Country

class CountryCreateFormModel(forms.ModelForm):
	class Meta:
		model = Country
		fields = ['name', 'code', 'continent', 'active']

people/forms.py
from django import forms
from people.models import Person
from django.forms import ModelForm
from countries.models import Country

class RegisterForm(forms.Form):
	first_name = forms.CharField(label='first name')
	nacionality = forms.ModelMultipleChoiceField(queryset=Country.objects.all())
	father = forms.ModelChoiceField(required=False, queryset=Person.objects.all())

class RegisterFormModel(forms.ModelForm):

	def __init__(self, fathers, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['father'].queryset = fathers

	class Meta:
		model = Person
		fields = ['first_name', 'nacionality', 'father']

continents/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from continents.models import Continent
# Create your views here.
class ContinentsView(ListView):
	template_name = 'continents/continents.html'
	model = Continent

	"""def get_context_data(self, *args, **kwargs):
		america = {'name':'américa', 'translation':'america', 'color':'#000000'}
		antartida = {'name':'antártida', 'translation':'antarctica', 'color':'#FFFF00'}
		europa = {'name':'europa', 'translation':'europe', 'color':'#F1D142'}
		africa = {'name':'africa', 'translation':'africa', 'color':'#F04261'}
		asia = {'name':'asia', 'translation':'asia', 'color':'#EE65EE'}
		oceania = {'name':'oceania', 'translation':'oceania', 'color':'#EE65DD'}

		continents = [
			america,
			africa,
			asia,
			oceania,
			antartida
		]

		return {'continents':continents}"""

countries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.views.generic import TemplateView
from countries.models import Country
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from countries.forms import CountryCreateFormModel

# Create your views here.

class HomeView(TemplateView):
	template_name = "countries/home.html"


class TagsView(TemplateView):
	template_name = "countries/tags.html"


class CountryDetailView(TemplateView):
	template_name = "countries/country_detail.html"


	def get_context_data(self, *args, **kwargs):
		code = kwargs['code']
		return {'code':code}

class CountryDetailIDView(DetailView):
	template_name = "countries/country_id_detail.html"

	model = Country

	"""def get_context_data(self, *args, **kwargs):
		country = get_object_or_404(Country, id=kwargs['id'])

		return {'country':country}"""

class CountrySearchView(ListView):
	template_name = 'countries/search.html'
	model = Country

	def get_queryset(self):
		query = self.kwargs['query']
		return Country.objects.filter(name__contains=query)


class CreateCountryView(TemplateView):
	template_name = "countries/register.html"

	def dispatch(self, request, *args, **kwargs):
		self.form = CountryCreateFormModel(request.POST or None)
		return super().dispatch(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		return {'form': self.form}

	def post(self, request, *args, **kwargs):	

		if self.form.is_valid():
			country = self.form.save()

			return JsonResponse({ "name":country.name })

		return self.get(request, *args, **kwargs)

people/views.py
from django.shortcuts import render
from django.http import JsonResponse
from people.forms import RegisterFormModel
from people.models import Person 
# Create your views here.
def register(request):
	fathers = Person.objects.filter(children__isnull=True)
	form = RegisterFormModel(fathers, request.POST or None)

	if form.is_valid():
		person = form.save()
		return JsonResponse({
			'name':person.first_name,
			'father': str(person.father),
			'nacionality': ','.join([str(country) for country in person.nacionality.all()])
			})
	return render(request, "people/register.html", {'form':form})

continents/templates/continents/continent.html
<div>
	<h1 style="color: {{ continent.color }}">{{ continent.name|title }}</h1>
	<p>
		Ingles: {{ continent.translate }} <br/>
		Details: 
	</p>
</div>

continents/templates/continents/continents.html
{% extends "countries/base.html" %}
{% block content %}
<h1>continents</h1>
{% for continent in object_list %}
	<hr>
	{% include 'continents/continent.html' %}
	<hr>
{% endfor %}
{% endblock %}

countries/templates/countries/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Geographic{% endblock %}</title>
		<style media="screen">
			div.a {
				background-color: lightblue;
			}
		</style>
	</head>
	<body>
		<div class="{% if request.session.testab == 'a' %} a {% endif %}">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

countries/templates/countries/country.html
<h1>nombre: {{country.name|title}}</h1>
<p>codigo: {{country.code}}</p>
{% if country.name == 'colombia' %}
	<p>yeah: {{country.code}}</p>
{% endif%}
<p>Detail_url <a href="{{ country.detail_url}}">Go to detail</a></p>
<br>

countries/templates/countries/country_detail.html
{% extends 'countries/base.html' %}
{% block content %}

{% for country in countries %}
	{% if country.code == code %}
		{% include 'countries/country.html'%}
	{% endif %}
{% endfor %}
{% endblock %}

countries/templates/countries/country_id_detail.html
{% extends 'countries/base.html' %}
{% block content %}

	{% include 'countries/country.html' with country=object %}

{% endblock %}

countries/templates/countries/home.html
{% extends "countries/base.html" %}

{% block title%}Home{% endblock %}

{% block content %}
	{% for country in countries %}
		{% include "countries/country.html" %}
	{% endfor %}

	<p><a href="{% url 'tags' %}">Go to tags</a></p>
	<p><a href="{% url 'continents:home' %}">Go to Continents</a></p>

	{{request.user}}
{% endblock %}

countries/templates/countries/register.html
{% extends "countries/base.html" %}

{% block content %}
	<h1>Register</h1>
	<form action="." method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="" value="Registrar">
	</form>
{% endblock %}

countries/templates/countries/search.html
{% extends "countries/base.html " %}
{% block content %}

	{% for country in object_list %}
		{% include "countries/country.html" %}
	{% endfor %}

{% endblock %}

countries/templates/countries/tags.html
{% extends "countries/base.html" %}

{% block content %}
	{% comment %} texto prueba {% endcomment %} <!--Template tag-->

	{% for country in countries %}
		<p>{{country}}</p>
		{% if country.name == 'colombia' %}
			Tierra querida
		{% endif %}
		<p>lorem: {% lorem %}</p>
		<p>fecha actual: {% now "Y-m-d" %}</p>
		{% filter force_escape|lower %}
			$%&$%& TEXTO
		{% endfilter %}

	{% endfor %}
{% endblock %}

people/templates/people/register.html
{% extends "countries/base.html" %}
{% block content %}

<form action="." method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="" value="Register">
	
</form>

{% endblock %}